package com.myspace.topic1.sampleproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SampleDO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SampleDO() {
    }




}